<a href="https://colab.research.google.com/github/GMartinez02/Big-Data---43C8-Fall-2024/blob/Concepts-as-Code/demo_Simple_PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import os

from google.colab import drive
drive.mount('/content/drive', force_remount=True)
curent_folder='Big Data - 43C8'
dest_folder='/content/drive/My Drive/'+curent_folder
os.chdir(dest_folder)
print('Path:',  os.getcwd())

Mounted at /content/drive
Path: /content/drive/My Drive/Big Data - 43C8


#PCA by Hand

###Step 1: calculating covariance matrix (unbiased)


In [ ]:
import numpy as np

X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1],
              [1,6,3]])
n,p = X.shape
print("data has " + str(n) + " observations "  + str(p) + " variables")
print(X)

data has 5 observations 3 variables
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]
 [1 6 3]]


In [ ]:
X_mean = np.mean(X,axis=0) #we need x_mean to get zero-mean data
print(X_mean)

[0.6 1.6 1.4]


In [ ]:
X_zero_mean_mat = X - X_mean #centering data: makes the mean of all the variables 0
print(X_zero_mean_mat)

[[-0.6 -1.6 -0.4]
 [-0.6 -0.6 -0.4]
 [ 0.4 -1.6 -0.4]
 [ 0.4 -0.6 -0.4]
 [ 0.4  4.4  1.6]]


In [ ]:
C = np.dot(X_zero_mean_mat.T,X_zero_mean_mat)/(n-1)
print("This is the covariance matrix")
print(C)

This is the covariance matrix
[[0.3  0.55 0.2 ]
 [0.55 6.3  2.2 ]
 [0.2  2.2  0.8 ]]


###Step 2: compute PCs and Variance (eigenvalue decomposition)

In [ ]:
Variance, PCs = np.linalg.eigh(C)
print("Variance")
print(Variance)
print("PCs")
print(PCs)

Variance
[0.02808232 0.25       7.12191768]
PCs
[[-2.98651724e-02 -9.95893206e-01 -8.54680805e-02]
 [-3.28516896e-01  9.05357460e-02 -9.40148886e-01]
 [ 9.44025805e-01 -3.05311332e-16 -3.29871611e-01]]


In [ ]:
#step 2.a :we sort eignevalues from largest to smallest
idx = np.argsort(-Variance)
Variance = Variance[idx]
print("Variance is sorted from largest to smallest")
print(Variance)

Variance
[7.12191768 0.25       0.02808232]


In [ ]:
#step 2.b :sort eigenvalues, PCs
PCs = PCs[:,idx]
print("Real PC matrix")
print(PCs)

Real PC matrix
[[-8.54680805e-02 -9.95893206e-01 -2.98651724e-02]
 [-9.40148886e-01  9.05357460e-02 -3.28516896e-01]
 [-3.29871611e-01 -3.05311332e-16  9.44025805e-01]]


###Step 3: verify PC matrix U is orthogonal


In [ ]:
#let U be the PC matrix
U = np.asmatrix(PCs)
print(U.T*U)
print("This is the identity matrix")

[[ 1.00000000e+00  1.08602874e-16 -8.32713696e-17]
 [ 1.08602874e-16  1.00000000e+00  9.00877935e-18]
 [-8.32713696e-17  9.00877935e-18  1.00000000e+00]]
This is the identity matrix


In [ ]:
#compute the newData (score) in the PCA space
newData = np.dot(X_zero_mean_mat,U)  #matrix multiplicaiton
print("the new data (score in the PCA space")
print(newData)

the new data (score in the PCA space
[[ 1.68746771e+00  4.52678730e-01  1.65935815e-01]
 [ 7.47318824e-01  5.43214476e-01 -1.62581081e-01]
 [ 1.60199963e+00 -5.43214476e-01  1.36070642e-01]
 [ 6.61850744e-01 -4.52678730e-01 -1.92446253e-01]
 [-4.69863691e+00 -2.62044343e-16  5.30208771e-02]]


In [ ]:
#verify newData with PCA from sklearn
from sklearn.decomposition import PCA
pca = PCA()
new_data = pca.fit_transform(X)
print("the new data (score) in the PCA space from sklearn \n", new_data)

the new data (score) in the PCA space from sklearn 
 [[-1.68746771e+00 -4.52678730e-01 -1.65935815e-01]
 [-7.47318824e-01 -5.43214476e-01  1.62581081e-01]
 [-1.60199963e+00  5.43214476e-01 -1.36070642e-01]
 [-6.61850744e-01  4.52678730e-01  1.92446253e-01]
 [ 4.69863691e+00 -8.69373453e-17 -5.30208771e-02]]


This isn't the same as the PCA from scratch, but it doesn't mattr since we just swapped the directions with the negative and positive signs.

#Dimensionality Reduction

Dimenions reduction affects variables (colunmns), we did projection, but didnt reduce dimensionality:
The 3rd column of 'new_data' will be dropped because it has the smallest variances